title: QMUL Bioinformatic Conference Deadlines
description: Countdown to bioinformatics conference abstract submission deadlines for QMUL
author: H Nicholls

#domain: "https://hlnicholls.github.io/bioinformatics-conferences/"
#baseurl: ""

github_username: hlnicholls
github_repo: bioinformatics-conferences

markdown: kramdown
ga_id:

include: ['_pages']
